name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # You can choose your desired version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional step, you can include testing)
      - name: Run tests
        run: |
          pytest  # Ensure you have tests in your repo

      # Step 5: Run the Streamlit app (if you'd like to test run in CI)
      - name: Run Streamlit App
        run: |
          streamlit run app.py  # Replace with the actual entry point of your Streamlit app
