name: Streamlit App Build and Deployment

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:  # Manual trigger option

concurrency:
  group: "streamlit-pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  STREAMLIT_ACCOUNT: your_streamlit_account_name  # Replace with your Streamlit Cloud account name
  STREAMLIT_APP_NAME: dirretta  # Replace with your Streamlit app name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      

      # Step 5: Run the Streamlit app (testing in CI)
      - name: Run Streamlit App
        run: |
          streamlit run app.py  # Replace with your actual Streamlit entry point

  deploy:
    needs: build-and-deploy  # Wait for build-and-deploy to finish
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # Deploy only on push
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
