name: CI/CD Pipeline for Streamlit App on Ploomber Cloud

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12  # Specify your Python version
  PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY }}  # Ensure you've added this as a GitHub secret

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ploomber Cloud Authentication
        run: ploomber-cloud key ${{ secrets.PLOOMBER_CLOUD_KEY }}

      - name: Deploy Streamlit App to Ploomber Cloud
        run: ploomber-cloud deploy

      - name: Verify Deployment Status
        run: ploomber-cloud status
