name: CI/CD Pipeline for Streamlit App

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12  # Specify your Python version
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies and Ploomber Cloud
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ploomber-cloud  # Install Ploomber Cloud

      - name: List project files
        run: ls -la  # List all files in the current directory

      - name: Configure Ploomber Cloud
        run: |
          ploomber-cloud key ${{ secrets.PLOOMBER_CLOUD_KEY }}  # Use the stored secret API key
          ploomber-cloud deploy  # Deploy the app to Ploomber Cloud
